@endpoint = https://house.cloud.smallsaas.cn


### 获取页面信息
GET {{endpoint}}/form?id=77777775

### 提交页面信息
POST {{endpoint}}/form/77777775
Content-Type: application/json

{  
    "version": "1",
    "name": "allPageList",
    "title": "个推页面",
    "pageStyle": {
    },
    "loadApi": "/form/allPages",
    "response": {
        "data": "data"
    },
    "request": {
    },
    "moduleContainer": {
        "height": "",
        "background": "#ffffff"
    },
    "modules": [
        {
            "type": "autolist",
            "name": "",
            "key": "a1a5efed-1372-4cfd-8087-91722f1023ba",
            "container": {
            }
        }
    ],
    "moduleData": {
        "a1a5efed-1372-4cfd-8087-91722f1023ba": {
            "loadApi": "/form/allPages",
            
            "newItemState": {
                "count": "count"
            },
            "multiItemNavigation": [
                "",
                "/appPage/updatePage?count",
                "",
            ],
            "multiNavigationModule": {
                "options": [
					{
						"option":"default",
						"label":"预览",
                        "spacer":"32"
					},
                    {
                        "option": "outline",
                        "label": "编辑"
                    },
                    {
                        "option": "warning",
                        "label": "删除"
                    }
                ]
            },

            "itemLayout": "wrap",

            "newItemModule": {
                "name": "addUserBuildingBtn",
            },
            "newItemNavigation": "/DynamicApplets/ListApps",

            "response": {
                "list": "records"
            },
            "request": {
                "default": {
                },
                "ps": "pageSize=30",
                "pn": "pageNum"
            },
            "itemModule": {
                "name": "allPageItem"
            }
        }
    }
}



